version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cth623_nhom4_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cth623_nhom4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cth623_nhom4_network

volumes:
  postgres_data:

networks:
  cth623_nhom4_network:
    driver: bridge
